# -*- Dockerfile -*-
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Berlin

RUN apt-get update \
    && apt-get -y -qq --no-install-recommends install \
    clang-format \
    git \
    && apt-get -yq clean \
    && rm --recursive --force /var/lib/apt/lists/*

WORKDIR /src
