# -*- Dockerfile -*-
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Berlin

RUN apt-get update \
    && apt-get -y -qq --no-install-recommends install \
    cmake \
    make \
    mpich \
    libmpich-dev \
    libxml2-dev \
    python3 \
    python3-pip \
# wrap wants to have python2. This is a bit sad. \
    python2 \
    gfortran \
    gcc \
    g++ \
    git \
    graphviz \
    libgtest-dev \
    llvm-12-tools \
    llvm-12-dev \
    && apt-get -yq clean \
    && rm --recursive --force /var/lib/apt/lists/* \
    && pip3 install --no-input --no-cache-dir --disable-pip-version-check 'lit>=14.0.0'

WORKDIR /src
