      PROGRAM typeresized

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C  @file
C
C  This program contains no MPI usage errors, hopefully ;)
C
C  @author Tobias Hilbrich
C
C  $ID$
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      IMPLICIT NONE

      INCLUDE "mpif.h"

      INTEGER ierror
      INTEGER newtype

      CALL MPI_INIT(ierror)

      CALL MPI_TYPE_CREATE_RESIZED(MPI_INTEGER, 0, 4, newtype, ierror)

      CALL MPI_TYPE_FREE (newtype, ierror)

      CALL MPI_FINALIZE(ierror)

      END
