stages:
- build
- test-minimal

include:
  - '/utility/.gitlab/cluster/cluster-template.yml'
  - '/utility/.gitlab/cluster/build.yml'

run-minimal-batch:
  extends:
    - .batch-tests-template
    - .cluster-tests-run
  stage: test-minimal
  variables:
    MAKE_CHECK_TARGET: "check-minimal"
    SLURM_TIMELIMIT: "00:05:00"
    END_SINGLE_SLURM_JOB: "1"
    REPORT_COLL_DIR: $REPORT_COLL_DIR
    CI_SUBMOD_COMMIT: $CI_SUBMOD_COMMIT
    CI_SUBMOD_TRIGGER: $CI_SUBMOD_TRIGGER

