include:
  - local: '/utility/.gitlab/common.yml'

stages:
- trigger

extended:
  stage: trigger
  variables:
    REPORT_COLL_DIR: $REPORT_COLL_DIR
    CI_SUBMOD_COMMIT: $_CI_SUBMOD_COMMIT
    CI_SUBMOD_TRIGGER: $_CI_SUBMOD_TRIGGER
  trigger:
    include: '/utility/.gitlab/cluster/sanitize-template.yml'
    strategy: depend
  parallel:
    matrix:
      - PARVAR_TOOLCHAIN: ["iimpi"]
        COMPILER: ["Clang/15.0.5"]
        SANITIZE_UBSAN: 'ON'
        SANITIZE_ASAN: 'OFF'
      - PARVAR_TOOLCHAIN: ["gompi"]
        COMPILER: ["None"]
        SANITIZE_UBSAN: 'OFF'
        SANITIZE_ASAN: 'ON'
      - PARVAR_TOOLCHAIN: ["mpich"]
        PRELOAD_MODULES: "GCC"
        SANITIZE_UBSAN: 'ON'
        SANITIZE_ASAN: 'ON'
