workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  MUST_BRANCH: develop

stages:
  - test
  - docs
  - compliance


formatting:
  stage: compliance
  needs: []
  image: ubuntu:23.04
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y --no-install-recommends git clang-format
  script:
    - git clang-format --verbose --diff ${CI_MERGE_REQUEST_DIFF_BASE_SHA}


docker:
  stage: test
  image: ubuntu:23.04
  parallel:
    matrix:
      # openmpi tests are broken at the moment
      # - MPI: [ mpich, openmpi ]
      - MPI: [ mpich ]
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - >-
      apt-get install -y --no-install-recommends
      gcc
      g++
      gfortran 
      cmake 
      make
      lib${MPI}-dev 
      git
      python3-minimal
      libxml2-dev
      gcovr
  variables:
    CMAKE_BUILD_TYPE: Debug
    OMPI_ALLOW_RUN_AS_ROOT: "1"
    OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: "1"
    OMPI_MCA_mpi_yield_when_idle: "1"
    OMPI_MCA_rmaps_base_oversubscribe: "1"
    CTEST_OUTPUT_ON_FAILURE: "1"
    EXTRA_CTEST_ARGS: ""
  script:
    - |
      if [[ "${MPI}" == "mpich" ]]
      then
        export EXTRA_CTEST_ARGS="${EXTRA_CTEST_ARGS} --label-exclude large_nproc"
      fi
    - cmake -S ./ -B build -DENABLE_COVERAGE=ON -DENABLE_TESTS=ON
    - cmake --build build
    - cmake --install build
    - ctest --test-dir build --output-junit junit.xml ${EXTRA_CTEST_ARGS}
  after_script:
    - mkdir -p build/coverage
    - gcovr -r ./ --print-summary --xml=build/cobertura.xml --html-details=build/coverage/index.html --exclude-directories '.*PnMPI.*'
  coverage: '/^lines: (.*\%)/'
  artifacts:
    reports:
      junit: build/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: build/cobertura.xml
    paths:
      - build/coverage/


must:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" 
  inherit:
    variables: false
  variables:
    CI_SUBMOD_COMMIT: $CI_COMMIT_SHA
    CI_SUBMOD_TRIGGER: $CI_PROJECT_NAME
  trigger:
    project: 'hpc-research/correctness/MUST'
    branch: $MUST_BRANCH
    strategy: depend
    

.batch-tests-template:
  variables:
    SLURM_CPUS_PER_TASK: "12"
    SLURM_OVERCOMMIT: "1"
    SLURM_ACCOUNT: "rwth1282"
    SLURM_CONSTRAINT: "Rocky8"
    SRUN_CPUS_PER_TASK: "12"
    SLURM_TIME: "00:30:00"
    CI_MODE: "Slurm"
    ENABLE_COVERAGE: "OFF"
  tags:
   - "unstable"
  before_script:
    - module purge
    - module use /home/pj416018/.modules
    - module use /home/ja664344/.modules/rl8
    - module load $PRELOAD_MODULES $PARVAR_TOOLCHAIN Python CMake
    - source .gitlab/envs/common.env
    - |
      if [[ "${LMOD_FAMILY_MPI}" == *"OpenMPI"* ]]
      then
        source .gitlab/envs/ompi.env
        export MPIEXEC_PREFLAGS="--oversubscribe"
      fi
    - |
      if [[ "${LMOD_FAMILY_MPI}" == *"impi"* ]]
      then
        source .gitlab/envs/impi.env
        export MPIEXEC_PREFLAGS="--launcher=ssh"
      fi
    - |
      if [[ "${LMOD_FAMILY_MPI}" == *"MPICH"* ]]
      then
        source .gitlab/envs/mpich.env
        export MPIEXEC_PREFLAGS="--launcher=ssh"
      fi

cluster:
  stage: test
  extends:
    - .batch-tests-template
  parallel:
    matrix:
      - PARVAR_TOOLCHAIN: ["mpich/dev", "OpenMPI/dev", 'gompi/2022a']
        ENABLE_COVERAGE: "ON"
      - PARVAR_TOOLCHAIN: ["iimpi/2022a"]
        ENABLE_COVERAGE: "OFF"
  variables:
    PRELOAD_MODULES: "GCC/11"
    CMAKE_BUILD_TYPE: Debug
    CTEST_OUTPUT_ON_FAILURE: "1"
  script:
    - !reference [.batch-tests-template, before_script]
    - cmake -S ./ -B build -DENABLE_COVERAGE=$ENABLE_COVERAGE -DENABLE_TESTS=ON -DMPIEXEC_PREFLAGS="${MPIEXEC_PREFLAGS}" -DCMAKE_INSTALL_PREFIX=install
    - cmake --build build -- -j ${SRUN_CPUS_PER_TASK}
    - cmake --install build
    - ctest --timeout 60 --test-dir build --output-junit junit.xml ${EXTRA_CTEST_ARGS}
  after_script:
    - mkdir -p build/coverage
    - |
      if [[ "${ENABLE_COVERAGE}" == "ON" ]]
      then
        module load Python
        gcovr -r ./ --print-summary --xml=build/cobertura.xml --html-details=build/coverage/index.html --exclude-directories '.*PnMPI.*'
      fi
  coverage: '/^lines: (.*\%)/'
  artifacts:
    reports:
      junit: build/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: build/cobertura.xml
    paths:
      - build/coverage/
      - build/Testing/Temporary/LastTest.log
    when: always


doxygen:
  stage: docs
  needs: [ ]
  image: ubuntu:23.04
  variables:
    CMAKE_BUILD_TYPE: Debug
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - >-
      apt-get install -y --no-install-recommends
      gcc
      g++
      gfortran 
      cmake 
      make
      libmpich-dev 
      git
      python3-minimal
      libxml2-dev
      doxygen
      graphviz
  script:
    - cmake -S ./ -B build
    - doxygen build/doc/developer.doxyfile
  after_script:
    - echo "The documentation can be viewed at ${CI_JOB_URL}/artifacts/file/build/doxygen/html/index.html"
  artifacts:
    paths:
      - build/doxygen/html/
