workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'

variables:
  MUST_BRANCH: develop 

stages:
- test

must:
  stage: test
  inherit:
    variables: false
  variables:
    CI_SUBMOD_COMMIT: $CI_COMMIT_SHA
    CI_SUBMOD_TRIGGER: $CI_PROJECT_NAME
  trigger:
    project: 'hpc-research/correctness/MUST'
    branch: $MUST_BRANCH
    strategy: depend

